var arrayName = ["Pippo" , "Paperino" , "Topolino", "Minnie" , "Pluto" , "Gabriele"]
var arrayCognome = ["Sanna" , "Casu" , "Aguilera" , "Patermo" , "Riccioli" , "D'Agata"]
document.getElementById("stampa").innerHTML += "</br>" + arrayName[parseInt(Math.floor(Math.random()*5))] + " " + arrayCognome[parseInt(Math.floor(Math.random()*5))]
document.getElementById("stampa").innerHTML += "</br>" + arrayName[parseInt(Math.floor(Math.random()*5))] + " " + arrayCognome[parseInt(Math.floor(Math.random()*5))]
document.getElementById("stampa").innerHTML += "</br>" + arrayName[parseInt(Math.floor(Math.random()*5))] + " " + arrayCognome[parseInt(Math.floor(Math.random()*5))]